language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION -no-share --warn update compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -no-share test
